from ubuntu:14.04

run apt-get update

run apt-get install -y mlton libgmp-dev make patch

ADD https://github.com/kayceesrk/multiMLton/archive/1971b0f74f0db4dce9bad077a9c79ee158933510.tar.gz /src.tgz

RUN tar xf /src.tgz 

#RUN cd /multiMLton-1971b0f74f0db4dce9bad077a9c79ee158933510/trunk && \
#    make all-no-docs



